services:
   mac.vmobile.repository.vala_mobile_repository:
    class: VMobile\Repository\ValaMobileRepository
    arguments: ["@doctrine"]
    public: true

  mac.vmobile.repository.vala_mobile_type_repository:
    class: Mac\VMobile\Repository\ValaMobileTypeRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]

    public: true

  mac.vmobile.repository.vala_mobile_compability_repository:
    class: Mac\VMobile\Repository\ValaMobileCompabilityRepository
    arguments: ["@doctrine"]
    public: true

  mac.vmobile.repository.vala_mobile_lang_repository:
    class: Mac\VMobile\Repository\ValaMobileLangRepository
    arguments: ["@doctrine"]
    public: true

  mac.vmobile.repository.vala_mobile_lang_type_repository:
    class: Mac\VMobile\Repository\ValaMobileLangTypeRepository
    arguments: ["@doctrine"]
    public: true

  mac.vmobile.repository.vala_mobile_manufacturer_repository:
    class: VMobile\Repository\ValaMobileManufacturerRepository
    arguments: ["@doctrine"]
    public: true
